### ISSUE TITLE
The datasets analyzed in the paper cannot be obtained 

### ISSUE THREAD

**Issue by xiaoli-0709** [JGuan-lab/scINRB#1]
The website https://zenodo.org/record/8224512 can't open again.
I am very interested in this. Is there any other way to obtain this data？

**Comment by JGuan-lab** [comment]
We have checked but there is no probelm with the website.

**Comment by xiaoli-0709** [comment]
Sorry, That's my probelm.Maybe there was a problem with my network, it's okay now。
Thank you
